name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Clean Build
        run: ./gradlew clean build > build_output.txt 2>&1

      - name: Determine release status and output to file
        if: ${{ runner.os == 'Linux' }}
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> build_output.txt
          else
            echo "STATUS=release" >> build_output.txt
          fi

      - name: Create a tarball of the entire project directory
        run: |
          echo "Creating a tarball of the project directory..."
          tar -czf project-artifacts.tar.gz .

      - name: Upload entire project directory as a tarball
        uses: actions/upload-artifact@v4
        with:
          name: full-project-artifacts
          path: project-artifacts.tar.gz
